networks:
  selenium-grid:
    driver: bridge

services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub-grid4
    restart: unless-stopped
    networks: [selenium-grid]
    
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"

    environment:
      - SE_OPTS=--external-url http://localhost:4444

      - SE_NEW_SESSION_WAIT_TIMEOUT=30
      - SE_SESSION_REQUEST_TIMEOUT=300
      - SE_SESSION_RETRY_INTERVAL=5
      - GRID_MAX_SESSION=50
      - GRID_BROWSER_TIMEOUT=300
      - GRID_TIMEOUT=300

    volumes:
      - /dev/shm:/dev/shm

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  chrome:
    image: selenium/node-chrome:latest
    shm_size: 2gb 
    restart: unless-stopped
    networks: [selenium-grid]

    depends_on:
      - selenium-hub

    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

      - SE_NODE_MAX_SESSIONS=6
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true

      - SE_NODE_GRID_URL=http://localhost:4444

      - SE_SCREEN_WIDTH=1280
      - SE_SCREEN_HEIGHT=720

    volumes:
      - /dev/shm:/dev/shm