# Cloudflare Workers 配置
# 部署前请修改 name 为你的项目名称
name = "testring-dev"
main = "src/cloudflare-worker.ts"
compatibility_date = "2025-07-28"

# Cloudflare Workers 原生支持 TypeScript，无需构建步骤
# [build]
# command = "npm run build:worker"

# 环境变量
[vars]
ENVIRONMENT = "production"