# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    strategy:
      matrix:
        node-version: [20, 22, 24]
        os: [ubuntu-latest, macos-latest, windows-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build:main

    # Install Playwright browsers for E2E tests
    - name: Install Playwright Browsers
      run: npx playwright install chromium

    # Run all tests with coverage
    - run: npm run test:ci:coverage

    # Display coverage summaries
    - name: Display Coverage Reports
      if: ${{ matrix.os=='ubuntu-latest' && matrix.node-version=='22'}}
      run: |
        echo "=== Unit Test Coverage Summary ==="
        if [ -f "./.coverage/lcov.info" ]; then
          echo "✅ Unit test coverage report generated"
          # Display basic coverage info
          grep -E "^(SF|LF|LH)" ./.coverage/lcov.info | head -20
        else
          echo "❌ Unit test coverage file not found"
        fi

        echo ""
        echo "=== E2E Test Coverage Summary ==="
        if [ -f "./c8-cov/lcov.info" ]; then
          echo "✅ E2E test coverage report generated"
          # Display basic coverage info
          grep -E "^(SF|LF|LH)" ./c8-cov/lcov.info | head -20
        else
          echo "❌ E2E test coverage file not found"
        fi

    - name: Upload Coverage to Coveralls
      if: ${{ matrix.os=='ubuntu-latest' && matrix.node-version=='22'}}
      uses: coverallsapp/github-action@master
      with:
        path-to-lcov: './c8-cov/lcov.info'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: SonarCloud Scan
      if: ${{ matrix.os=='ubuntu-latest' && matrix.node-version=='22' && github.event.pull_request.merged == true}}
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
