name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to publish
        default: 0.8.0
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Configure git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Get commit info
        id: commit_info
        run: |
          echo "commit_id=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "github_username=${{ github.actor }}" >> $GITHUB_OUTPUT

      - name: Check publish target
        id: check_publish_target
        run: |
          if [[ "${{ github.repository }}" != "ringcentral/testring" ]] || [[ "${{ github.ref }}" != "refs/heads/master" ]]; then
            if [[ -n "${{ secrets.NPM_TOKEN }}" ]]; then
              echo "should_publish_dev=true" >> $GITHUB_OUTPUT
              echo "Publishing to dev packages because:"
              echo "  Repository: ${{ github.repository }} (not ringcentral/testring)"
              echo "  Branch: ${{ github.ref }} (not refs/heads/master)"
              echo "  NPM_TOKEN is available"
            else
              echo "should_publish_dev=false" >> $GITHUB_OUTPUT
              echo "Not publishing: NPM_TOKEN not available"
            fi
          else
            echo "should_publish_dev=false" >> $GITHUB_OUTPUT
            echo "Publishing to production packages (ringcentral/testring master branch)"
          fi

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install chromium

      - name: Build project
        run: npm run build:main

      - name: Publish to production
        if: steps.check_publish_target.outputs.should_publish_dev == 'false'
        run: |
          npm run publish:version ${{ github.event.inputs.version }}
          npm run publish:ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to dev packages
        if: steps.check_publish_target.outputs.should_publish_dev == 'true'
        run: |
          npm run publish:dev -- --github-username=${{ steps.commit_info.outputs.github_username }} --commit-id=${{ steps.commit_info.outputs.commit_id }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
